### ISSUE TITLE
Role validation bug

### ISSUE THREAD

**Issue by tyrellj** [erayd/libec#3]
It is possible to add roles or grants not contained by a parent cert. ec_cert_check() with EC_CHECK_ROLE does not properly validate that the signer certificate has a grant for roles and grants on a certificate because the record loop is not actually checking any records on the cert.

ec_cert_check is checking the wrong section name on records, and does not end up validating any roles/grants from the certificate in question as it's checking "_grant" and "_role" rather than "$_grant" and "$_role"

See the following lines in ec_cert_check:

```
//iterate grants
for(ec_record_t *r = ec_record_match_bin(ec_cert_records(c), "_grant", 0, NULL, 0, NULL, 0);
  r && !(r->flags & EC_RECORD_SECTION); r = r->next)

//iterate roles
for(ec_record_t *r = ec_record_match_bin(ec_cert_records(c), "_role", 0, NULL, 0, NULL, 0);
  r && !(r->flags & EC_RECORD_SECTION); r = r->next)
```

**Comment by erayd** [comment]
Good catch, thanks! Looks like I forgot to update this when I moved roles / grants into a sign-required section.
